<?php

/**
 * @file
 * Allows automatic switching of Solr servers based on the current environemnt.
 */

include_once dirname(__FILE__) . '/acquia_search_multi_subs.common.inc';

/**
 * Implements hook_init().
 *
 * Includes the two module-specific include files and calls their init functions
 * if their respective module is enabled.
 *
 * @see acquia_search_multi_subs_apachesolr_init()
 * @see acquia_search_multi_subs_searchapi_init()
 */
function acquia_search_multi_subs_init() {
  if (module_exists('search_api_acquia')) {
    include_once dirname(__FILE__) . '/lib/Drupal/SearchApiSolr/acquia_search_multi_subs.searchapisolr.inc';
    acquia_search_multi_subs_searchapi_init();
  }
  if (module_exists('acquia_search')) {
    include_once dirname(__FILE__) . '/lib/Drupal/Apachesolr/acquia_search_multi_subs.apachesolr.inc';
    acquia_search_multi_subs_apachesolr_init();
  }
}

/**
 * Implements hook_acquia_subscription_status().
 *
 * Needed to reinforce our overridden config settings.
 */
function acquia_search_multi_subs_acquia_subscription_status($active, $subscription = FALSE) {
  if ($active) {
    acquia_search_multi_subs_init();
  }
}
