<?php

/**
 * @file
 * Module state handling for the Acquia Search Multi Subscription module.
 */

/**
 * Implements hook_uninstall().
 *
 * Remove variables from any environment that would have this information
 */
function acquia_search_multi_subs_uninstall() {
  if (module_exists('apachesolr')) {
    variable_del('apachesolr_environments');
    $environments = apachesolr_load_all_environments();
    foreach ($environments as $environment) {
      apachesolr_environment_variable_del($environment['env_id'], 'acquia_search');
      apachesolr_environment_variable_del($environment['env_id'], 'acquia_search_key');
      apachesolr_environment_variable_del($environment['env_id'], 'acquia_override_subscription_corename');
      apachesolr_environment_variable_del($environment['env_id'], 'acquia_override_selector');
      apachesolr_environment_variable_del($environment['env_id'], 'acquia_override_subscription_key');
      apachesolr_environment_variable_del($environment['env_id'], 'acquia_override_subscription_id');
      apachesolr_environment_variable_del($environment['env_id'], 'acquia_override_auto_switch');
    }
  }
}

/**
 * Implements hook_disable().
 *
 * Remove config overrides.
 */
function acquia_search_multi_subs_disable() {
  // We want to also remove all config overrides when we disable it to avoid
  // confusion.
  acquia_search_multi_subs_uninstall();
}
