<?php
/**
 * @file
 * Exposes functionality for manually cropping an image.
 */

require_once 'manualcrop.helpers.inc';
require_once 'manualcrop.admin.inc';

/**
 * Implements hook_permission().
 */
function manualcrop_permission() {
  return array(
    'administer manualcrop settings' => array(
      'title' => t('Administer Manual Crop'),
      'description' => t('Allows users to change the global Manual Crop settings.'),
      'restrict access' => FALSE,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function manualcrop_menu() {
  $items = array();

  $items['admin/config/media/manualcrop'] = array(
    'title' => 'Manual Crop',
    'description' => 'Configure the global Manual Crop options.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('manualcrop_global_settings_form'),
    'access arguments' => array('administer manualcrop settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'manualcrop.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function manualcrop_theme() {
  return array(
    'manualcrop_crop_and_scale_summary' => array(
      'variables' => array('data' => NULL),
    ),
    'manualcrop_crop_summary' => array(
      'variables' => array('data' => NULL),
    ),
    'manualcrop_reuse_summary' => array(
      'variables' => array('data' => NULL),
    ),
    'manualcrop_auto_reuse_summary' => array(
      'variables' => array('data' => NULL),
    ),
    'manualcrop_croptool_overlay' => array(
      'variables' => array('attributes' => NULL, 'image' => NULL, 'crop_info' => TRUE, 'instant_preview' => FALSE),
    ),
    'manualcrop_croptool_inline' => array(
      'variables' => array('attributes' => NULL, 'image' => NULL, 'crop_info' => TRUE, 'instant_preview' => FALSE),
    ),
    'manualcrop_thumblist' => array(
      'variables' => array('attributes' => NULL, 'images' => NULL),
    ),
    'manualcrop_thumblist_image' => array(
      'variables' => array('attributes' => NULL, 'image' => NULL, 'style' => NULL),
    ),
  );
}

/**
 * Implements hook_help().
 */
function manualcrop_help($path) {
  switch ($path) {
    case 'admin/config/media/image-styles/edit/%':
      return '<p>' . t("<strong>Note:</strong> if you are using a Manual Crop effect, it's forced to be the only Manual Crop effect and first effect in the list.") . '</p>';
  }
}

/**
 * Implements hook_views_api().
 */
function manualcrop_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'manualcrop') . '/includes/views',
  );
}

/**
 * Implements hook_libraries_info().
 */
function manualcrop_libraries_info() {
  $libraries = array();

  $libraries['jquery.imagesloaded'] = array(
    'name' => 'jQuery imagesLoaded',
    'vendor url' => 'http://desandro.github.io/imagesloaded',
    'version callback' => 'manualcrop_library_get_version',
    'version arguments' => array(
      'file' => array(
        'jquery.imagesloaded.js',
        'jquery.imagesloaded.min.js',
      ),
      'pattern' => '# v([0-9\.]+)#',
      'lines' => 5,
      'cols' => 40,
    ),
    'files' => array(
      'js' => array(
        'jquery.imagesloaded.js',
      ),
    ),
    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'jquery.imagesloaded.min.js',
          ),
        ),
        'variant callback' => 'manualcrop_library_detect_variant',
        'variant arguments' => array(),
      ),
    ),
  );

  $libraries['jquery.imgareaselect'] = array(
    'name' => 'jQuery imgAreaSelect',
    'vendor url' => 'http://odyniec.net/projects/imgareaselect',
    'version callback' => 'libraries_get_version',
    'version arguments' => array(
      'file' => 'scripts/jquery.imgareaselect.js',
      'pattern' => '#version ([0-9\.]+)#',
      'lines' => 10,
      'cols' => 20,
    ),
    'files' => array(
      'js' => array(
        'scripts/jquery.imgareaselect.js',
      ),
      'css' => array(
        'css/imgareaselect-animated.css',
      ),
    ),
    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'scripts/jquery.imgareaselect.min.js',
          ),
          'css' => array(
            'css/imgareaselect-animated.css',
          ),
        ),
        'variant callback' => 'manualcrop_library_detect_variant',
        'variant arguments' => array(),
      ),
      'packed' => array(
        'files' => array(
          'js' => array(
            'scripts/jquery.imgareaselect.pack.js',
          ),
          'css' => array(
            'css/imgareaselect-animated.css',
          ),
        ),
        'variant callback' => 'manualcrop_library_detect_variant',
        'variant arguments' => array(),
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_image_style_delete().
 */
function manualcrop_image_style_delete($style) {
  $style_name = (isset($style['old_name']) ? $style['old_name'] : $style['name']);

  if (!empty($style['effects'])) {
    $effect = reset($style['effects']);

    if (_manualcrop_is_own_effect($effect, TRUE)) {
      // Delete the crop selections.
      db_delete('manualcrop')
        ->condition('style_name', $style_name)
        ->execute();

      // Update the style name in the field widgets.
      _manualcrop_update_style_name_in_field_widget($style_name);
    }
  }

  // Update the style name in the image effects.
  _manualcrop_update_style_name_in_image_effect($style_name);
}

/**
 * Implements hook_image_style_flush().
 */
function manualcrop_image_style_flush($style) {
  if (!empty($style['effects'])) {
    $effect = reset($style['effects']);
    if (_manualcrop_is_own_effect($effect)) {
      // Leave if this style has a Manual Crop effect.
      return;
    }
  }

  // Delete all crop selections if the image style doesn't have a Manual Crop
  // effect. We do this here because there's no image effect delete hook.
  db_delete('manualcrop')
    ->condition('style_name', (isset($style['old_name']) ? $style['old_name'] : $style['name']))
    ->execute();
}

/**
 * Implements hook_file_delete().
 */
function manualcrop_file_delete($file) {
  db_delete('manualcrop')->condition('fid', $file->fid)->execute();
}

/**
 * Implements hook_field_widget_info_alter().
 */
function manualcrop_field_widget_info_alter(&$info) {
  foreach (manualcrop_supported_widgets() as $widget_type) {
    if (isset($info[$widget_type]['settings'])) {
      $settings = &$info[$widget_type]['settings'];
      $settings += manualcrop_default_widget_settings();

      if ($settings['manualcrop_styles_mode'] == 'exclude' && !empty($settings['manualcrop_styles_list'])) {
        // Check if all styles are excluded.
        $styles = manualcrop_styles_with_crop();
        $styles = array_diff_key($styles, $settings['manualcrop_styles_list']);

        if (empty($styles)) {
          $settings['manualcrop_enable'] = FALSE;
        }
      }
    }
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function manualcrop_field_widget_form_alter(&$element, &$form_state, $context) {
  $widget = $context['instance']['widget'];

  if (manualcrop_supported_widgets($widget['type'])) {
    if ($widget['type'] == 'media_generic') {
      // We don't check if Manual Crop is enabled, this happens in the file
      // enntity edit form.
      $element['#after_build'][] = 'manualcrop_media_element_process';
    }
    elseif (!empty($widget['settings']['manualcrop_enable'])) {
      // Check if this field instance is attached to a Field Collection item
      // entity, if so we prepare the form only once.
      if (_manualcrop_check_field_collection_form_prepare($context['instance'])) {
        manualcrop_croptool_prepare_form($element, $form_state, manualcrop_js_identifier($context['instance']), $widget['settings']);
      }

      // Default, add a process and validate callback for each child.
      foreach (element_children($element) as $key) {
        $element[$key]['#process'][] = 'manualcrop_widget_process';
        $element[$key]['#element_validate'][] = 'manualcrop_croptool_validate';
        $element[$key]['#element_validate'][] = 'file_managed_file_validate';
      }

      if (module_exists('insert')) {
        $element['#after_build'][] = 'manualcrop_insert_element_process';
      }
    }
  }
}

/**
 * Implements hook_field_attach_submit().
 */
function manualcrop_field_attach_submit($entity_type, $entity, $form, &$form_state) {
  manualcrop_croptool_submit($form, $form_state);
}

/**
 * Implements hook_manualcrop_supported_widgets().
 */
function manualcrop_manualcrop_supported_widgets() {
  return array(
    'image_image' => array('thumblist', 'inline_crop', 'instant_crop'),
    'image_miw' => array('thumblist', 'inline_crop', 'instant_crop'),
    'media_generic' => array('thumblist', 'inline_crop'),
  );
}

/**
 * Process function for Manual Crop enabled widgets.
 *
 * @param $element
 *   The form element.
 * @param $form_state
 *   The form state array.
 * @param $form
 *   The complete form.
 *
 * @return
 *   Altered widget element.
 */
function manualcrop_widget_process($element, &$form_state, $form) {
  if (!empty($element['#file'])) {
    // Get the field instance.
    $instance = field_info_instance($element['#entity_type'], $element['#field_name'], $element['#bundle']);

    // Add the croptool.
    manualcrop_croptool_process($element, $form_state, manualcrop_js_identifier($instance), $element['#file'], $instance);
  }

  return $element;
}

/**
 * Prepare the form that will hold the croptool.
 *
 * @param $form
 *   The form structure array.
 * @param $form_state
 *   The form state array.
 * @param $js_identifier
 *   Unique javascript crop settings identifier.
 * @param $settings
 *   Widget settings.
 */
function manualcrop_croptool_prepare_form(&$form, &$form_state, $js_identifier, $settings = array()) {
  if (!empty($_COOKIE['has_js']) || variable_get('manualcrop_skip_js_check', FALSE)) {
    $styles = &drupal_static(__FUNCTION__);

    if (!is_array($styles)) {
      $styles = array();

      // Generate image style settings.
      foreach (manualcrop_styles_with_crop() as $style_name => $data) {
        $styles[$style_name] = array(
          'effect' => $data['effect']['name'],
          'data' => $data['effect']['data']
        );
      }
    }

    // Load the default settings.
    if (!is_array($settings) || empty($settings)) {
      $settings = manualcrop_default_widget_settings();
    }

    // Add the javascript settings.
    $form['#attached']['js'][] = array('data' => array('manualCrop' => array(
      'styles' => $styles,
      'fields' => array(
        $js_identifier => array(
          'required' => manualcrop_instance_required_styles($settings),
          'instantCrop' => !empty($settings['manualcrop_instant_crop']),
          'defaultCropArea' => !empty($settings['manualcrop_default_crop_area']),
          'maximizeDefaultCropArea' => !empty($settings['manualcrop_maximize_default_crop_area']),
        ),
      ),
    )), 'type' => 'setting');

    // IE has problems with lazy loading of css files, see http://drupal.org/node/1071818
    if (!empty($_SERVER['HTTP_USER_AGENT']) && strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE') !== FALSE) {
      $form['#attached']['css'][] = drupal_get_path('module', 'manualcrop') . '/manualcrop.css';
      $form['#attached']['manualcrop_library_load'][] = array('jquery.imgareaselect');
    }

    // Reset the images array.
    if (!isset($form_state['manualcrop_data'])) {
      $form_state['manualcrop_data'] = array('images' => array());
    }
    else {
      $form_state['manualcrop_data']['images'] = array();
    }
  }
}

/**
 * Add a croptool to the form element. This extends the FAPI widget or simply adds
 * a new form item to enable cropping in a regular form.
 *
 * @param $element
 *   Form element to be processed. This should be the form array for none FAPI fields.
 * @param $form_state
 *   The form state array.
 * @param $js_identifier
 *   Unique javascript crop settings identifier.
 * @param $file
 *   The file object.
 * @param $instance
 *   Field instance array.
 * @param $settings
 *   Used to pass-in (additional) widget settings, these settings will
 *   override the instance settings.
 * @param $preview
 *   Name of the preview element.
 *
 * @return
 *    Returns TRUE if a croptool has been added, FALSE otherwise.
 */
function manualcrop_croptool_process(&$element, &$form_state, $js_identifier, $file, $instance = NULL, $settings = array(), $preview = 'preview') {
  if (isset($form_state['manualcrop_data']) && $file->filemime != 'application/pdf') {
    $styles = manualcrop_styles_with_crop();

    if (!empty($styles)) {
      // Make sure $settings is an array.
      if (!is_array($settings)) {
        $settings = array();
      }

      // Load the instance or default settings.
      if (is_array($instance)) {
        $settings += $instance['widget']['settings'];
      }
      else {
        $settings += manualcrop_default_widget_settings();
      }

      // Required image styles.
      $required = manualcrop_instance_required_styles($settings);

      // Exclude or include styles.
      if (!empty($settings['manualcrop_styles_list'])) {
        // Filter hidden styles.
        if ($settings['manualcrop_styles_mode'] == 'include') {
          $styles = array_intersect_key($styles, $settings['manualcrop_styles_list']);
        }
        else {
          $styles = array_diff_key($styles, $settings['manualcrop_styles_list']);
        }

        if (empty($styles)) {
          // Leave if all styles were filtered.
          return FALSE;
        }
      }

      // Overlay or inline cropping.
      if (!empty($settings['manualcrop_inline_crop'])) {
        $crop_type = 'inline';
      }
      else {
        $crop_type = 'overlay';
      }

      // Check if the preview element exists.
      if (!empty($preview) && isset($element[$preview])) {
        // Thumbnail list, so no preview image.
        if (!empty($settings['manualcrop_thumblist'])) {
          unset($element[$preview]);
          $preview = NULL;
        }
      }
      else {
        $preview = NULL;
      }

      if (is_array($instance)) {
        // A FAPI field instance has been passed, so $element is the container
        // and $element['#value'] can be used for storing data.
        $container = &$element;
        $item = &$element['#value'];
      }
      else {
        // The FAPI is not used, we'll create a global manualcrop container as
        // parent for all manualcrop enabled files.
        if (!isset($element['manualcrop'])) {
          $element['manualcrop'] = array(
            '#tree' => TRUE,
          );
        }

        // Create a file specific container.
        $element['manualcrop']['file_' . $file->fid] = array(
          '#type' => 'value',
          '#default_value' => array(),
          '#element_validate' => array('manualcrop_croptool_validate'),
          '#parents' => array('manualcrop', 'file_' . $file->fid),
        );

        // Link to the newly created container and item.
        $container = &$element['manualcrop']['file_' . $file->fid];
        $item = &$container['#default_value'];
      }

      // Add a prefix and suffix to the preview image.
      if (!empty($preview)) {
        $element[$preview]['#prefix'] = '<div class="manualcrop-preview manualcrop-preview-' . $file->fid . '"><div class="manualcrop-preview-cropped"></div>';
        $element[$preview]['#suffix'] = '</div>';
      }

      // Get image info, width and height are used by the cropping widget.
      $image = image_get_info($file->uri);

      // Save some image data to improve processing.
      $form_state['manualcrop_data']['images'][$file->fid] = array(
        'uri' => $file->uri,
        'filename' => $file->filename,
        'width' => $image['width'],
        'height' => $image['height'],
        'element_parents' => $container['#parents'],
        'required_styles' => $required,
      );

      // Get the crop selections for this file.
      $submitted = (isset($form_state['inline_entity_form']) ? FALSE : $form_state['submitted']);
      if (!$submitted && !isset($item['manualcrop_selections'])) {
        $item['manualcrop_selections'] = array();
        foreach (manualcrop_load_crop_selection($file->uri) as $data) {
          $item['manualcrop_selections'][$data->style_name] = $data->x . '|' . $data->y . '|' . $data->width . '|' . $data->height;
        }
      }

      // Add a css class
      $container['#attributes']['class'][] = 'manualcrop-file-' . $file->fid . '-holder';

      // Original image for cropping.
      $container['manualcrop_' . $crop_type] = array(
        '#type' => 'markup',
        '#markup' => theme('manualcrop_croptool_' . $crop_type, array(
          'attributes' => array(
            'id' => array('manualcrop-' . $crop_type . '-' . $file->fid),
            'class' => array('manualcrop-' . $crop_type, 'element-hidden'),
          ),
          'image' => array(
            'path' => $file->uri,
            'alt' => $file->filename,
            'width' => $image['width'],
            'height' => $image['height'],
            'attributes' => array('class' => array('manualcrop-image')),
          ),
          'crop_info' => !empty($settings['manualcrop_crop_info']),
          'instant_preview' => !empty($settings['manualcrop_instant_preview']),
        )),
      );

      // Image style options.
      $style_options = array('' => t('Select a style to crop'));

      // Hidden fields to save the crop selection, one for each image style.
      foreach ($styles as $style_name => $info) {
        $container['manualcrop_selections'][$style_name] = array(
          '#type' => 'hidden',
          '#default_value' => (isset($item['manualcrop_selections'][$style_name]) ? $item['manualcrop_selections'][$style_name] : ''),
          '#attributes' => array(
            'id' => 'manualcrop-area-' . $file->fid . '-' . $style_name,
            'class' => array('manualcrop-cropdata'),
            'onchange' => 'ManualCrop.selectionStored(this, ' . $file->fid . ', \'' . $style_name . '\');',
          ),
        );

        $style_options[$style_name] = $info['label'];
      }

      // Default form element options.
      $defaults = array(
        '#weight' => (isset($container['title']['#weight']) ? $element['title']['#weight'] : 1),
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'manualcrop') . '/manualcrop.css',
          ),
          'js' => array(
            drupal_get_path('module', 'manualcrop') . '/manualcrop.js',
          ),
          'manualcrop_library_load' => array(
            array('jquery.imagesloaded'),
            array('jquery.imgareaselect'),
          )
        ),
      );

      // Element to open the croptool.
      if (!empty($settings['manualcrop_thumblist'])) {
        // Thumbnail list, each image style is transformed in a clickable thumbnail.
        array_shift($style_options);
        foreach ($style_options as $style_name => $style_clean_name) {
          $prefix = '<span class="manualcrop-preview manualcrop-preview-' . $file->fid . ' manualcrop-preview-' . $file->fid . '-' . $style_name . '"><span class="manualcrop-preview-cropped"></span>';
          $suffix = '</span>';

          $style_options[$style_name] = theme('manualcrop_thumblist_image', array(
            'style' => $style_clean_name,
            'image' => $prefix . theme('image_style', array(
              'path' => $file->uri,
              'alt' => $file->filename,
              'width' => $image['width'],
              'height' => $image['height'],
              'style_name' => $style_name,
            )) . $suffix,
            'attributes' => array(
              'class' => array_merge(
                array(
                  'manualcrop-style-thumb',
                  'manualcrop-style-thumb-' . $file->fid,
                  'manualcrop-style-thumb-' . $file->fid . '-' . $style_name,
                  'manualcrop-style-preview-' . $file->fid,
                  'manualcrop-style-preview-' . $file->fid . '-' . $style_name
                ),
                (in_array($style_name, $required) ? array('manualcrop-style-required') : array())
              ),
              'href' => 'javascript:void(0);',
              'onmousedown' => "ManualCrop.showCroptool('" . $js_identifier . "', '" . $style_name . "', " . $file->fid . ");",
              'onclick' => 'return false;',
            ),
          ));
        }

        $container['manualcrop_style'] = array_merge($defaults, array(
          '#markup' => theme('manualcrop_thumblist', array(
            'attributes' => array(
              'class' => array('manualcrop-thumblist', 'manualcrop-thumblist-' . $file->fid),
            ),
            'images' => $style_options,
          )),
        ));
      }
      elseif (count($style_options) == 2) {
        // Only one style, display a button.
        end($style_options);
        $style_name = key($style_options);

        $container['manualcrop_style'] = array_merge($defaults, array(
          '#type' => 'button',
          '#value' => t('Crop'),
          '#attributes' => array(
            'class' => array_merge(array('manualcrop-style-button', 'manualcrop-style-button-' . $file->fid), (in_array($style_name, $required) ? array('manualcrop-style-required') : array())),
            'onmousedown' => "ManualCrop.showCroptool('" . $js_identifier . "', '" . $style_name . "', " . $file->fid . ");",
            'onclick' => 'return false;',
          ),
          '#prefix' => '<div class="manualcrop-style-button-holder">',
          '#suffix' => '</div>',
        ));
      }
      else {
        // Style selection list.
        $container['manualcrop_style'] = array_merge($defaults, array(
          '#type' => 'select',
          '#title' => t('Manual Crop'),
          '#description' => t('Select the image style to crop, the corresponding cropping tool will open.'),
          '#options' => $style_options,
          '#multiple' => FALSE,
          '#attributes' => array(
            'class' => array(
              'manualcrop-identifier-' . $js_identifier,
              'manualcrop-style-select',
              'manualcrop-style-select-' . $file->fid
            ),
            'onchange' => "ManualCrop.showCroptool('" . $js_identifier . "', this, " . $file->fid . ");",
          ),
        ));
      }

      // The FAPI widget can have a alt and/or title field, increase their weight.
      if (isset($container['alt'])) {
        $container['alt']['#weight']++;
      }

      if (isset($container['title'])) {
        $container['title']['#weight']++;
      }

      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Additional after build callback to modify form elements added by the Insert module.
 *
 * @param $element
 *   The element to process.
 */
function manualcrop_insert_element_process($element) {
  foreach (element_children($element) as $key) {
    if (!empty($element[$key]['insert']['#options']) && !empty($element[$key]['manualcrop_selections'])) {
      $settings = $element[$key]['insert']['#widget']['settings'];

      // Increase the select list weight.
      $element[$key]['insert']['#weight'] = 0;

      if (!empty($settings['manualcrop_filter_insert'])) {
        // Make a list of all styles that should be visible in the widget.
        $styles = array('image' => 1);
        foreach (element_children($element[$key]['manualcrop_selections']) as $style) {
          $styles['image_' . $style] = 1;
        }

        // Filter hidden styles from Insert.
        $element[$key]['insert']['#options'] = array_intersect_key($element[$key]['insert']['#options'], $styles);

        // Make sure the default value is allowed.
        if (!array_key_exists($element[$key]['insert']['#default_value'], $element[$key]['insert']['#options'])) {
          reset($element[$key]['insert']['#options']);
          $element[$key]['insert']['#default_value'] = key($element[$key]['insert']['#options']);
        }
      }
    }
  }

  return $element;
}

/**
 * Implements of hook_insert_content().
 */
function manualcrop_insert_content($item, $style, $widget) {
  return image_insert_content($item, $style, $widget);
}

/**
 * Additional after build callback to modify the Media widget.
 *
 * @param $element
 *   The element to process.
 */
function manualcrop_media_element_process($element) {
  $data = array(
    'manualcrop' => array(
      'entity_type' => $element['#entity_type'],
      'bundle' => $element['#bundle'],
      'field_name' => $element['#field_name'],
    )
  );

  // Add the options to the element.
  $element['#media_options']['global'] += $data;

  // Attach the options as javascript settings.
  $media = &$element['#attached']['js'][1]['data']['media'];
  $media['elements'][$element['#id']]['global'] += $data;

  // Modify the "Edit" link.
  if (!empty($element['edit'])) {
    $element['edit']['#href'] = url('media/' . $element['fid']['#value'] . '/edit/nojs', array('query' => $data, 'absolute' => TRUE));
  }

  return $element;
}

/**
 * Validation handler to validate each cropping selection.
 *
 * @param $element
 *   The element array.
 * @param $form_state
 *   The form state array.
 */
function manualcrop_croptool_validate($element, &$form_state) {
  if (!empty($form_state['manualcrop_data']['images']) && (!isset($form_state['triggering_element']) || !in_array($form_state['triggering_element']['#value'], array(t('Upload'), t('Remove'))))) {
    // Create a new key, to store processed selections, in the data array.
    $form_state['manualcrop_data']['selections'] = array();
    $selections = &$form_state['manualcrop_data']['selections'];

    // Loop trough the positions to get the Manual Crop data.
    foreach ($form_state['manualcrop_data']['images'] as $fid => $image) {
      $value = drupal_array_get_nested_value($form_state['values'], $image['element_parents']);

      if (!empty($value['manualcrop_selections'])) {
        // Create a selections array for the current image, the first element is
        // the path to the original image, needed for flushing the cache.
        $selections[$fid] = array(
          'path' => $image['uri'],
          'styles' => array_fill_keys(array_keys($value['manualcrop_selections']), FALSE),
        );

        // Indicates if an error on the form element has been set.
        $error_set = FALSE;

        // Loop over the selections.
        foreach ($value['manualcrop_selections'] as $style_name => $crop) {
          // Get the clean style name.
          $clean_style_name = _manualcrop_image_style_label($style_name);

          // Get the element key.
          if (!$error_set) {
            $element_key = implode('][', $image['element_parents']) . '][manualcrop_style';
          }
          else {
            $element_key = implode('][', $image['element_parents']) . '][manualcrop_selections][' . $style_name;
          }

          if (!empty($crop)) {
            // Validate the crop selection format.
            if (preg_match('/^([0-9]+\|){3}[0-9]+$/', $crop)) {
              $crop = array_map('intval', explode('|', $crop));

              // Check position and minimum dimensions.
              if ($crop[0] >= 0 && $crop[1] >= 0 && $crop[2] > 0 && $crop[3] > 0) {
                // Check if the selections fits on the image.
                if (($crop[0] + $crop[2]) <= $image['width'] && ($crop[1] + $crop[3]) <= $image['height']) {
                  $selections[$fid]['styles'][$style_name] = array(
                    'x' => $crop[0],
                    'y' => $crop[1],
                    'width' => $crop[2],
                    'height' => $crop[3],
                  );
                  continue;
                }
              }
            }

            // Invalid crop selection.
            $error_set = TRUE;
            form_set_error($element_key, t('The crop selection for %filename (@style image style) is invalid, please clear it or reselect.', array(
              '@style' => $clean_style_name,
              '%filename' => $image['filename']
            )));
          }
          elseif (in_array($style_name, $image['required_styles'], TRUE)) {
            // Uncropped required style.
            $error_set = TRUE;
            form_set_error($element_key, t('%filename must have a cropping selection for the @style image style.', array(
              '@style' => $clean_style_name,
              '%filename' => $image['filename']
            )));
          }
        }
      }
    }
  }
}

/**
 * Submit handler to save each crop selection.
 *
 * @param $form
 *   The form structure array.
 * @param $form_state
 *   The form state array.
 */
function manualcrop_croptool_submit($form, &$form_state) {
  if (!empty($form_state['manualcrop_data']['selections'])) {
    // Loop trough the selections to save them.
    foreach ($form_state['manualcrop_data']['selections'] as $fid => $data) {
      db_delete('manualcrop')
        ->condition('fid', $fid)
        ->condition('style_name', array_keys($data['styles']))
        ->execute();

      foreach ($data['styles'] as $style_name => $selection) {
        if ($selection) {
          db_insert('manualcrop')
            ->fields(array_merge($selection, array(
              'fid' => $fid,
              'style_name' => $style_name
            )))
            ->execute();
        }
      }

      // Clear the cached versions of this image.
      image_path_flush($data['path']);
    }

    if (variable_get('manualcrop_cache_control', TRUE)) {
      // Clear the cached image paths.
      cache_clear_all('manualcrop:', 'cache', TRUE);
    }

    // Show a success message when not using the FAPI.
    if (!empty($form['manualcrop'])) {
      drupal_set_message(t('The crop selections have been saved.'));
    }

    // Unset the form state data to prevent submitting twice.
    unset($form_state['manualcrop_data']);
  }
}

/**
 * Preprocessing for theme_image(); Force reloading of an image after re-cropping.
 *
 * @param $variables
 *   Image template variables.
 */
function manualcrop_preprocess_image(&$variables) {
  // Is cache control enabled?
  if (!empty($variables['style_name']) && variable_get('manualcrop_cache_control', TRUE)) {
    $styles = manualcrop_styles_with_crop(TRUE);
    $style_name = $variables['style_name'];

    // Does this image style have a Manual Crop effect?
    if (isset($styles[$style_name])) {
      $original_path = $variables['path'];

      // Attempt to load the HTTP cache-controller from cache.
      $cache_key = 'manualcrop:' . md5($original_path);
      if ($cached_path = cache_get($cache_key)) {
        $variables['path'] = $cached_path->data;
      }
      else {
        // No HTTP cache-controller in cache, get the image path.
        $match = '/styles/' . $style_name . '/';
        $path = substr($variables['path'], (strrpos($variables['path'], $match) + drupal_strlen($match)));
        $path = explode('/', $path);

        // Build the image URI.
        $scheme = array_shift($path);
        $target = implode('/', $path);
        $image_uri = $scheme . '://' . urldecode($target);

        // Use the reuse style to load the crop selection.
        $effect = $styles[$style_name]['effect'];
        if (_manualcrop_is_own_effect($effect, FALSE)) {
          switch ($effect['name']) {
            case 'manualcrop_reuse':
              $style_name = $effect['data']['reuse_crop_style'];
              break;
            case 'manualcrop_auto_reuse':
              // The fallback style doesn't have a crop selection.
              unset($style_name);

              // Get the first applied crop selection.
              if ($crop = manualcrop_load_crop_selection($image_uri)) {
                $crop = reset($crop);
              }
              break;
          }
        }

        // Load the cropping area.
        if (empty($crop) && isset($style_name)) {
          $crop = manualcrop_load_crop_selection($image_uri, $style_name);
        }

        if (!empty($crop)) {
          // Add a HTTP cache-controller to the image path.
          $variables['path'] .= (strpos($variables['path'], '?') !== FALSE ? '&' : '?') . 'c=' . md5($crop->x . '|' . $crop->y . '|' . $crop->width . '|' . $crop->height);

          // Cache the the updated image path.
          cache_set($cache_key, $variables['path']);
        }
      }
    }
  }
}

/**
 * Returns HTML for the overlay crop area of an image.
 *
 * @param $variables
 *   An associative array containing:
 *   - "attributes": An array of attributes.
 *   - "image": An array of variables for the image theming function.
 *
 * @return
 *   HTML for the overlay crop tool.
 *
 * @ingroup themeable
 */
function theme_manualcrop_croptool_overlay($variables) {
  $output = '<div ' . drupal_attributes($variables['attributes']) . '>';

  $output .= '<div class="manualcrop-overlay-bg"></div>';

  $output .= '<div class="manualcrop-image-holder">';
  $output .= theme('image', $variables["image"]);
  $output .= '</div>';

  if ($variables['crop_info']) {
    $output .= '<div class="manualcrop-selection-info hidden">';
    $output .= '<div class="manualcrop-selection-label manualcrop-selection-xy">';
    $output .= '<div class="manualcrop-selection-label-content">';
    $output .= '<span class="manualcrop-selection-x">-</span> x <span class="manualcrop-selection-y">-</span>';
    $output .= '</div>';
    $output .= '</div>';
    $output .= '<div class="manualcrop-selection-label manualcrop-selection-width">';
    $output .= '<div class="manualcrop-selection-label-content">-</div>';
    $output .= '</div>';
    $output .= '<div class="manualcrop-selection-label manualcrop-selection-height">';
    $output .= '<div class="manualcrop-selection-label-content">-</div>';
    $output .= '</div>';
    $output .= '</div>';
  }

  if ($variables['instant_preview']) {
    $output .= '<div class="manualcrop-instantpreview"></div>';
  }

  $output .= '<div class="manualcrop-style-info">';
  $output .= t('Image style') . ': <span class="manualcrop-style-name">&nbsp;</span>';
  $output .= '</div>';

  $output .= '<div class="manualcrop-buttons">';
  $output .= '<a class="manualcrop-button manualcrop-cancel" href="javascript:void(0);" onmousedown="ManualCrop.closeCroptool(true);">' . t('Cancel') . '</a>';
  $output .= '<a class="manualcrop-button manualcrop-maximize" href="javascript:void(0);" onmousedown="ManualCrop.maximizeSelection();">' . t('Maximize selection') . '</a>';
  $output .= '<a class="manualcrop-button manualcrop-clear" href="javascript:void(0);" onmousedown="ManualCrop.clearSelection();">' . t('Remove selection') . '</a>';
  $output .= '<a class="manualcrop-button manualcrop-reset" href="javascript:void(0);" onmousedown="ManualCrop.resetSelection();">' . t('Revert selection') . '</a>';
  $output .= '<a class="manualcrop-button manualcrop-close" href="javascript:void(0);" onmousedown="ManualCrop.closeCroptool();">' . t('Save') . '</a>';
  $output .= '</div>';

  $output .= '</div>';

  return $output;
}

/**
 * Returns HTML for the inline crop area of an image.
 *
 * @param $variables
 *   An associative array containing:
 *   - "attributes": An array of attributes.
 *   - "image": An array of variables for the image theming function.
 *
 * @return
 *   HTML for the inline crop tool.
 *
 * @ingroup themeable
 */
function theme_manualcrop_croptool_inline($variables) {
  $output = '<div ' . drupal_attributes($variables['attributes']) . '>';

  $output .= '<div class="manualcrop-image-holder">';
  $output .= theme('image', $variables['image']);
  $output .= '</div>';

  $output .= '<div class="clearfix">';

  if ($variables['crop_info']) {
    $output .= '<div class="manualcrop-selection-info hidden">';
    $output .= '<div class="manualcrop-selection-label manualcrop-selection-xy">';
    $output .= '<div class="manualcrop-selection-label-content">';
    $output .= '<span class="manualcrop-selection-x">-</span> x <span class="manualcrop-selection-y">-</span>';
    $output .= '</div>';
    $output .= '</div>';
    $output .= '<div class="manualcrop-selection-label manualcrop-selection-width">';
    $output .= '<div class="manualcrop-selection-label-content">-</div>';
    $output .= '</div>';
    $output .= '<div class="manualcrop-selection-label manualcrop-selection-height">';
    $output .= '<div class="manualcrop-selection-label-content">-</div>';
    $output .= '</div>';
    $output .= '</div>';
  }

  if ($variables['instant_preview']) {
    $output .= '<div class="manualcrop-instantpreview"></div>';
  }

  if ($variables['crop_info']) {
    $output .= '<div class="manualcrop-style-info">';
    $output .= t('Image style') . ': <span class="manualcrop-style-name">&nbsp;</span><br />';
    $output .= '</div>';
  }

  $output .= '<div class="manualcrop-buttons">';
  $output .= '<input type="button" value="' . t('Save') . '" class="manualcrop-button manualcrop-close form-submit" onmousedown="ManualCrop.closeCroptool();" />';
  $output .= '<input type="button" value="' . t('Revert selection') . '" class="manualcrop-button manualcrop-reset form-submit" onmousedown="ManualCrop.resetSelection();" />';
  $output .= '<input type="button" value="' . t('Remove selection') . '" class="manualcrop-button manualcrop-clear form-submit" onmousedown="ManualCrop.clearSelection();" />';
  $output .= '<input type="button" value="' . t('Maximize selection') . '" class="manualcrop-button manualcrop-maximize form-submit" onmousedown="ManualCrop.maximizeSelection();" />';
  $output .= '<input type="button" value="' . t('Cancel') . '" class="manualcrop-button manualcrop-cancel form-submit" onmousedown="ManualCrop.closeCroptool(true);" />';
  $output .= '</div>';

  $output .= '</div>';

  $output .= '</div>';

  return $output;
}

/**
 * Returns HTML for thumbnail list.
 *
 * @param $variables
 *   An associative array containing:
 *   - "attributes": An array of attributes.
 *   - "images": Array of images html, themed by the "manualcrop_thumblist_image" function an keyed by style name.
 *
 * @return
 *   HTML for the thumb list.
 *
 * @ingroup themeable
 */
function theme_manualcrop_thumblist($variables) {
  $output = '<div ' . drupal_attributes($variables['attributes']) . '>';
  $output .= '<div class="clearfix">';
  $output .= implode('', $variables['images']);
  $output .= '</div>';
  $output .= '</div>';

  return $output;
}

/**
 * Returns HTML for a single image in the thumbnail list.
 *
 * @param $variables
 *   An associative array containing:
 *   - "attributes": An array of attributes.
 *   - "image": Rendered image tag html.
 *   - "style": Clean style name.
 *
 * @return
 *   HTML for a single thumblist image.
 *
 * @ingroup themeable
 */
function theme_manualcrop_thumblist_image($variables) {
  $output = '<a ' . drupal_attributes($variables['attributes']) . '>';
  $output .= '<strong class="manualcrop-style-thumb-label">' . check_plain($variables['style']) . '</strong>';
  $output .= $variables['image'];
  $output .= '</a>';

  return $output;
}

/**
 * Implements hook_image_effect_info().
 */
function manualcrop_image_effect_info() {
  return array(
    'manualcrop_crop_and_scale' => array(
      'label' => t('Manual Crop: Crop and scale'),
      'help' => t('Crop and scale a user-selected area, respecting the ratio of the destination width and height.'),
      'effect callback' => 'manualcrop_crop_and_scale_effect',
      'form callback' => 'manualcrop_crop_and_scale_form',
      'summary theme' => 'manualcrop_crop_and_scale_summary',
    ),
    'manualcrop_crop' => array(
      'label' => t('Manual Crop: Custom crop'),
      'help' => t('Crop a freely user-selected area.'),
      'effect callback' => 'manualcrop_crop_effect',
      'form callback' => 'manualcrop_crop_form',
      'summary theme' => 'manualcrop_crop_summary',
    ),
    'manualcrop_reuse' => array(
      'label' => t('Manual Crop: Reuse cropped style'),
      'help' => 'Reuse a crop selection from another Manual Crop enabled image style.',
      'effect callback' => 'manualcrop_reuse_effect',
      'form callback' => 'manualcrop_reuse_form',
      'summary theme' => 'manualcrop_reuse_summary',
    ),
    'manualcrop_auto_reuse' => array(
      'label' => t('Manual Crop: Automatically reuse cropped style'),
      'help' => 'Load the first applied crop selection and reuse it.',
      'effect callback' => 'manualcrop_auto_reuse_effect',
      'form callback' => 'manualcrop_auto_reuse_form',
      'summary theme' => 'manualcrop_auto_reuse_summary',
    ),
  );
}

/**
 * Image effect callback; Crop and scale an image resource.
 *
 * @param $image
 *   An image object returned by image_load().
 * @param $data
 *   An array of attributes, needed to perform the crop and scale effect, with
 *   the following items:
 *   - "width": An integer representing the desired width in pixels.
 *   - "height": An integer representing the desired height in pixels.
 *   - "upscale": A boolean indicating that the image should be upscalled if
 *     the dimensions are larger than the original image.
 *   - "onlyscaleifcrop": A boolean indicating that the image should only be scaled
 *     if it was cropped.
 *   - "style_name": The style's machine name.
 *
 * @return
 *   TRUE on success, FALSE on failure to crop and scale image.
 *
 * @see image_crop_effect()
 * @see image_scale_effect()
 */
function manualcrop_crop_and_scale_effect(&$image, $data) {
  // The width and height will be possibly overwritten for the cropping,
  // so copy the data array for later.
  $scale_data = $data;
  $crop = manualcrop_load_crop_selection($image->source, $data['style_name']);

  if ($crop) {
    // Only crop if a crop was applied.
    $data['width'] = $crop->width;
    $data['height'] = $crop->height;
    $data['anchor'] = $crop->x . '-' . $crop->y;

    if (!image_crop_effect($image, $data)) {
      return FALSE;
    }
  }
  elseif (!empty($data['onlyscaleifcrop'])) {
    return TRUE;
  }
  else {
    // Automated crop, don't use image_scale_and_crop_effect() unless both
    // imagedimensions are bigger than the desired dimensions. This way
    // unwanted upscaling is prevented.
    if ($image->info['width'] > $scale_data['width'] && $image->info['height'] > $scale_data['height']) {
      if (!image_scale_and_crop_effect($image, $scale_data)) {
        return FALSE;
      }
    }
    else if (!image_crop_effect($image, $scale_data)) {
      return FALSE;
    }
  }

  return image_scale_effect($image, $scale_data);
}

/**
 * Image effect callback; Crop an image resource.
 *
 * @param $image
 *   An image object returned by image_load().
 * @param $data
 *   An array of attributes, needed to perform the crop effect, with the
 *   following items:
 *   - "width": An integer representing the desired width in pixels.
 *   - "height": An integer representing the desired height in pixels.
 *   - "style_name": The style's machine name.
 *
 * @return
 *   TRUE on success, FALSE on failure to crop image.
 *
 * @see image_crop_effect()
 */
function manualcrop_crop_effect(&$image, $data) {
  $crop = manualcrop_load_crop_selection($image->source, $data['style_name']);

  if ($crop) {
    $data['width'] = $crop->width;
    $data['height'] = $crop->height;
    $data['anchor'] = $crop->x . '-' . $crop->y;

    return image_crop_effect($image, $data);
  }
  elseif (!empty($data['reuse_crop_style'])) {
    return manualcrop_reuse_effect($image, $data);
  }

  return TRUE;
}

/**
 * Image effect callback; Reuse the crop effect of another image style.
 *
 * @param $image
 *   An image object returned by image_load().
 * @param $data
 *   An array of settings, needed to perform the reuse effect, with the
 *   following items:
 *   - "reuse_crop_style": Name of the image style to reuse the crop effect of.
 *
 * @return
 *   TRUE on success, FALSE when the crop effect couldn't be reused.
 *
 * @see image_crop_effect()
 */
function manualcrop_reuse_effect(&$image, $data) {
  if (empty($data['reuse_crop_style'])) {
    return FALSE;
  }

  // Get the first image style effect.
  $style = image_style_load($data['reuse_crop_style']);
  $effect = reset($style['effects']);

  if ($effect) {
    image_effect_apply($image, $effect);
    return TRUE;
  }

  return FALSE;
}

/**
 * Image effect callback; Search for a Manual Crop effect with a crop selection
 * and reuse it.
 *
 * @param $image
 *   An image object returned by image_load().
 * @param $data
 *   An array of settings, needed to perform the select effect, with the
 *   following items:
 *   - "fallback_style": The image style to use when no crop selection was found.
 *
 * @return
 *   TRUE on success, FALSE on failure to select the effect.
 *
 * @see image_crop_effect()
 */
function manualcrop_auto_reuse_effect(&$image, $data) {
  // Get the crop selections for this file.
  $crop = manualcrop_load_crop_selection($image->source);

  if ($crop) {
    // Load and apply the Manual Crop effect.
    $style = image_style_load(reset($crop)->style_name);
    $effect = reset($style['effects']);

    return image_effect_apply($image, $effect);
  }
  elseif (!empty($data['fallback_style'])) {
    // Load and apply all effects of the fallback style.
    $style = image_style_load($data['fallback_style']);
    foreach ($style['effects'] as $effect) {
      if (!image_effect_apply($image, $effect)) {
        return FALSE;
      }
    }
  }

  return TRUE;
}

/**
 * Implements hook_insert_styles().
 */
function manualcrop_insert_styles() {
  $insert_styles = &drupal_static(__FUNCTION__);

  if (is_null($insert_styles)) {
    $styles = manualcrop_styles_with_crop(FALSE, NULL, TRUE);
    $insert_styles = array();

    foreach ($styles as $style_name => $label) {
      $insert_styles['image_' . $style_name] = array(
        'label' => $label,
      );
    }
  }

  return $insert_styles;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Provides integration with the File Entity (and Media) module by adding the
 * crop functionality to the file upload form.
 */
function manualcrop_form_file_entity_add_upload_alter(&$form, &$form_state) {
  if (isset($form['#step']) && $form['#step'] == 4) {
    // Get the field instance information.
    $instance_info = array();
    if (!empty($form_state['build_info']['args'][0]['manualcrop'])) {
      $instance_info = $form_state['build_info']['args'][0]['manualcrop'];
    }

    // Process the form.
    _manualcrop_process_file_entity_form($form, $form_state, $instance_info, $form['#entity']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Provides integration with the File Entity (and Media) module by adding the
 * crop functionality to the file edit form.
 */
function manualcrop_form_file_entity_edit_alter(&$form, &$form_state) {
  if ($form['type']['#value'] == 'image' && !empty($form['preview']['#file'])) {
    // Try to parse the GET parameter if's missing.
    if (!isset($_GET['manualcrop']) && strpos($_GET['q'], '?') !== FALSE) {
      parse_str('q=' . str_replace('?', '&', $_GET['q']), $_GET);
    }

    // Process the form.
    _manualcrop_process_file_entity_form($form, $form_state, (isset($_GET['manualcrop']) ? $_GET['manualcrop'] : array()), $form['preview']['#file']);
  }
}
